version: '2'
services:
  fu-test-db:
    image: mysql:5.7
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: cristian
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: fu_app_test_development
      MYSQL_HOST: fu-test-db
  fu-test:
    build: .
    command: bash -c "sleep 40 && rm -f tmp/pids/server.pid && bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails s -p 2700 -b '0.0.0.0'"
    ports:
      - "2700:2700"
    depends_on:
      - fu-test-db
    volumes:
        - SharedFolderContainers:/SharedStorage
volumes:
    SharedFolderContainers:
        external: true
